### ISSUE TITLE
Bundled versioneer is not compatible with Python 3.12

### ISSUE THREAD

**Issue by bnavigator** [gwpy/ligotimegps#22]
Hi,

not sure whether this package is still maintained. FWIW, it is still a dependency of gwpy.

The bundled versioneer.py is too old for Python 3.12. Trying to install from the sdist produces:

```
[   16s] + /usr/bin/python3.12 setup.py build '--executable=/usr/bin/python3.12 -s'
[   16s] /home/abuild/rpmbuild/BUILD/ligotimegps-2.0.1/versioneer.py:485: SyntaxWarning: invalid escape sequence '\s'
[   16s]   LONG_VERSION_PY['git'] = '''
[   16s] Traceback (most recent call last):
[   16s]   File "/home/abuild/rpmbuild/BUILD/ligotimegps-2.0.1/setup.py", line 29, in <module>
[   16s]     __version__ = versioneer.get_version()
[   16s]                   ^^^^^^^^^^^^^^^^^^^^^^^^
[   16s]   File "/home/abuild/rpmbuild/BUILD/ligotimegps-2.0.1/versioneer.py", line 1473, in get_version
[   16s]     return get_versions()["version"]
[   16s]            ^^^^^^^^^^^^^^
[   16s]   File "/home/abuild/rpmbuild/BUILD/ligotimegps-2.0.1/versioneer.py", line 1406, in get_versions
[   16s]     cfg = get_config_from_root(root)
[   16s]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[   16s]   File "/home/abuild/rpmbuild/BUILD/ligotimegps-2.0.1/versioneer.py", line 412, in get_config_from_root
[   16s]     parser = configparser.SafeConfigParser()
[   16s]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   16s] AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

Python 3.12 removed the long deprecated `SafeConfigParser`.

One solution would be to  replace versioneer.py by a newer one.
I have seen other projects migrating to another method of keeping track of the version, so I am not sure if a PR involving versioneer would be worthwhile.

**Comment by bnavigator** [comment]
Gah, this time **I** read things too quickly. This was already fixed by #18

(But never released)
